// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconEpFold: typeof import('~icons/ep/fold')['default']
    'IconFa:weixin': typeof import('~icons/fa/weixin')['default']
    'IconIc:baseline10k': typeof import('~icons/ic/baseline10k')['default']
    'IconLineMd:sunnyOutlineLoop': typeof import('~icons/line-md/sunny-outline-loop')['default']
    'IconLineMd:sunnyOutlineToMoonAltLoopTransition': typeof import('~icons/line-md/sunny-outline-to-moon-alt-loop-transition')['default']
    IconMaterialSymbols10k: typeof import('~icons/material-symbols/10k')['default']
    'IconMdi:aboutCircleOutline': typeof import('~icons/mdi/about-circle-outline')['default']
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
    'IconMdi:shieldLockOutline': typeof import('~icons/mdi/shield-lock-outline')['default']
    'IconMdi:signIn': typeof import('~icons/mdi/sign-in')['default']
    'IconMdi:twitter': typeof import('~icons/mdi/twitter')['default']
    'IconRi:24HoursFill': typeof import('~icons/ri/24-hours-fill')['default']
    'IconTabler:homeCheck': typeof import('~icons/tabler/home-check')['default']
    'IconVscodeIcons:fileTypeWxss': typeof import('~icons/vscode-icons/file-type-wxss')['default']
    NButton: typeof import('naive-ui')['NButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
