/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconAntDesign:fullscreenExitOutlined': typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
    'IconAntDesign:fullscreenOutlined': typeof import('~icons/ant-design/fullscreen-outlined')['default']
    'IconAntDesign:settingOutlined': typeof import('~icons/ant-design/setting-outlined')['default']
    'IconFa:weixin': typeof import('~icons/fa/weixin')['default']
    'IconLineMd:menuFoldLeft': typeof import('~icons/line-md/menu-fold-left')['default']
    'IconLineMd:menuFoldRight': typeof import('~icons/line-md/menu-fold-right')['default']
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
    'IconMdi:shieldLockOutline': typeof import('~icons/mdi/shield-lock-outline')['default']
    'IconMdi:signIn': typeof import('~icons/mdi/sign-in')['default']
    'IconMdi:twitter': typeof import('~icons/mdi/twitter')['default']
    'IconMdiLight:settings': typeof import('~icons/mdi-light/settings')['default']
    'IconUil:alignJustify': typeof import('~icons/uil/align-justify')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleApp: typeof import('./src/components/common/SingleApp.vue')['default']
  }
}
