name: Build and Deploy
# 监听 main 分支的推送
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # job 名
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 运行步骤
    steps:
      # 获取源码
      - name: Checkout
        uses: actions/checkout@v2.3.1
      # 下载依赖
      - name: Install dependencies and Build
        run: npm install && npm run build:mock
      # 发布
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          # 发布在 gh-pages 分支，会自动创建
          branch: gh-pages
          # 将打包后的 dist 目录放到 gh-pages 分支
          folder: dist
